version: '3'
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=mydatabase
      - ADMIN_PASS=${ADMIN_PASS}  # This will be replaced with the value from .env
      - ADMIN_NAME=${ADMIN_NAME}  # This will be replaced with the value from .env

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase

volumes:
  mongodb_data: